import {INPUTTYPE, POSITION, SEVERITY, SIZE, VARIANT, STYLETYPE, ALIGN } from "@Enums";
import { ORIENTATION } from "@/components/atoms/ADivider/enums";

type Align =
  | ALIGN.CENTER
  | ALIGN.LEFT
  | ALIGN.RIGHT;

type InputType =
  | INPUTTYPE.BUTTON
  | INPUTTYPE.CHECKBOX
  | INPUTTYPE.COLOR
  | INPUTTYPE.DATE
  | INPUTTYPE.DATETIME_LOCAL
  | INPUTTYPE.EMAIL
  | INPUTTYPE.FILE
  | INPUTTYPE.HIDDEN
  | INPUTTYPE.IMAGE
  | INPUTTYPE.MONTH
  | INPUTTYPE.NUMBER
  | INPUTTYPE.PASSWORD
  | INPUTTYPE.RADIO
  | INPUTTYPE.RANGE
  | INPUTTYPE.RESET
  | INPUTTYPE.SEARCH
  | INPUTTYPE.SUBMIT
  | INPUTTYPE.TEL
  | INPUTTYPE.TEXT
  | INPUTTYPE.TIME
  | INPUTTYPE.URL
  | INPUTTYPE.WEEK;

type Orientation =
  | ORIENTATION.HORIZONTAL
  | ORIENTATION.VERTICAL;

type Position =
  | POSITION.BOTTOM
  | POSITION.LEFT
  | POSITION.RIGHT
  | POSITION.TOP;

type Severity =
  | SEVERITY.CONTRAST
  | SEVERITY.DANGER
  | SEVERITY.HELP
  | SEVERITY.INFO
  | SEVERITY.PRIMARY
  | SEVERITY.SECONDARY
  | SEVERITY.SUCESS
  | SEVERITY.WARN;

type Size =
  | SIZE.LARGE
  | SIZE.NORMAL
  | SIZE.SMALL;

type StyleType =
  | STYLETYPE.DASHED
  | STYLETYPE.DOTTED
  | STYLETYPE.SOLID;

type Variant =
  | VARIANT.CONTAINED
  | VARIANT.FILLED
  | VARIANT.OUTLINED
  | VARIANT.TEXT;


export type { Align, InputType, Orientation, Position, Severity, Size, StyleType, Variant };
export { ALIGN, INPUTTYPE, ORIENTATION, POSITION, SEVERITY, SIZE, STYLETYPE, VARIANT };
