import { POSITION, SEVERITY, SIZE, VARIANT, ORIENTATION, STYLETYPE, ALIGN } from "@Enums";

type Position = POSITION.BOTTOM | POSITION.LEFT | POSITION.RIGHT | POSITION.TOP;

type Severity =
  | SEVERITY.CONTRAST
  | SEVERITY.DANGER
  | SEVERITY.HELP
  | SEVERITY.INFO
  | SEVERITY.PRIMARY
  | SEVERITY.SECONDARY
  | SEVERITY.SUCESS
  | SEVERITY.WARN;

type Size = SIZE.LARGE | SIZE.NORMAL | SIZE.SMALL;

type Variant = VARIANT.CONTAINED | VARIANT.OUTLINED | VARIANT.TEXT;

type Orientation = ORIENTATION.HORIZONTAL | ORIENTATION.VERTICAL;

type StyleType = STYLETYPE.DASHED | STYLETYPE.DOTTED | STYLETYPE.SOLID

type Align = ALIGN.LEFT | ALIGN.CENTER | ALIGN.RIGHT;

export type { Position, Severity, Size, Variant, Orientation, StyleType, Align };
export { POSITION, SEVERITY, SIZE, VARIANT, ORIENTATION, STYLETYPE, ALIGN };
