import { ALIGN, INPUT_TYPE, INPUT_MASK_PATTERN, ORIENTATION, POSITION, SEVERITY, SIZE, STYLETYPE, VARIANT } from "@Enums";

type Align =
  | ALIGN.CENTER
  | ALIGN.LEFT
  | ALIGN.RIGHT

type InputType =
  | INPUT_TYPE.BUTTON
  | INPUT_TYPE.CHECKBOX
  | INPUT_TYPE.COLOR
  | INPUT_TYPE.DATE
  | INPUT_TYPE.DATETIME_LOCAL
  | INPUT_TYPE.EMAIL
  | INPUT_TYPE.FILE
  | INPUT_TYPE.HIDDEN
  | INPUT_TYPE.IMAGE
  | INPUT_TYPE.MONTH
  | INPUT_TYPE.NUMBER
  | INPUT_TYPE.PASSWORD
  | INPUT_TYPE.RADIO
  | INPUT_TYPE.RANGE
  | INPUT_TYPE.RESET
  | INPUT_TYPE.SEARCH
  | INPUT_TYPE.SUBMIT
  | INPUT_TYPE.TEL
  | INPUT_TYPE.TEXT
  | INPUT_TYPE.TIME
  | INPUT_TYPE.URL
  | INPUT_TYPE.WEEK

type InputMaskPattern =
  | INPUT_MASK_PATTERN.CELLPHONE
  | INPUT_MASK_PATTERN.CEP
  | INPUT_MASK_PATTERN.CNPJ
  | INPUT_MASK_PATTERN.CPF
  | INPUT_MASK_PATTERN.CREDIT_CARD
  | INPUT_MASK_PATTERN.DATE
  | INPUT_MASK_PATTERN.PHONE

type Orientation =
  | ORIENTATION.HORIZONTAL
  | ORIENTATION.VERTICAL

type Position =
  | POSITION.BOTTOM
  | POSITION.LEFT
  | POSITION.RIGHT
  | POSITION.TOP

type Severity =
  | SEVERITY.CONTRAST
  | SEVERITY.DANGER
  | SEVERITY.HELP
  | SEVERITY.INFO
  | SEVERITY.PRIMARY
  | SEVERITY.SECONDARY
  | SEVERITY.SUCESS
  | SEVERITY.WARN

type Size =
  | SIZE.LARGE
  | SIZE.NORMAL
  | SIZE.SMALL

type StyleType =
  | STYLETYPE.DASHED
  | STYLETYPE.DOTTED
  | STYLETYPE.SOLID

type Variant =
  | VARIANT.CONTAINED
  | VARIANT.FILLED
  | VARIANT.OUTLINED
  | VARIANT.TEXT


export type { Align, InputType, InputMaskPattern, Orientation, Position, Severity, Size, StyleType, Variant };
export { ALIGN, INPUT_TYPE, INPUT_MASK_PATTERN, ORIENTATION, POSITION, SEVERITY, SIZE, STYLETYPE, VARIANT };
